import argparse
import xml.etree.ElementTree as ET
from pathlib import Path

import pandas as pd

from utils import ensure_parent, timestamp_now_utc


FIELDS = [
    "source_row_index",
    "original_scene_id",
    "stac_item_id",
    "timestamp",
    "lat",
    "lon",
    "category_name",
    "original_matched_category",
    "polarization",
    "center_x",
    "center_y",
    "patch_file",
    "patch_cal_file",
    "patch_uint8_file",
    "patch_rgb_file",
    "patch_status",
]


def text_value(value):
    if pd.isna(value):
        return ""
    return str(value)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--metadata_csv",
        default="data/opensarship_like/metadata/dataset_metadata.csv",
    )
    parser.add_argument("--output_xml", default="data/opensarship_like/XML/Ship.xml")
    args = parser.parse_args()

    df = pd.read_csv(args.metadata_csv)
    if "patch_status" in df.columns:
        ship_df = df[df["patch_status"].astype(str).str.lower() == "success"].copy()
    else:
        ship_df = df.copy()

    root = ET.Element("ShipPatchDataset")
    root.set("generated_at_utc", timestamp_now_utc())
    root.set("description", "Dataset patch metadata generated by pipeline, not original Sentinel-1 XML")

    for index, row in ship_df.iterrows():
        ship = ET.SubElement(root, "Ship")
        ship.set("id", str(index))
        ship.set("patch_name", text_value(row.get("patch_name", "")))
        ship.set("category", text_value(row.get("category_name", "")))
        ship.set("polarization", text_value(row.get("polarization", "")))

        for field in FIELDS:
            element = ET.SubElement(ship, field)
            element.text = text_value(row.get(field, ""))

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    output_xml = Path(args.output_xml)
    ensure_parent(output_xml)
    tree.write(output_xml, encoding="utf-8", xml_declaration=True)
    print(f"Ship XML: {output_xml}")
    print(f"Jumlah patch sukses dalam XML: {len(ship_df)}")


if __name__ == "__main__":
    main()
