import argparse
import xml.etree.ElementTree as ET
from pathlib import Path

import pandas as pd

from utils import ensure_parent, timestamp_now_utc


def text_value(value):
    if pd.isna(value):
        return ""
    return str(value)


def add_text(parent, name, value):
    element = ET.SubElement(parent, name)
    element.text = text_value(value)
    return element


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--metadata_csv",
        default="data/opensarship_like/metadata/dataset_metadata.csv",
    )
    parser.add_argument("--output_xml", default="data/opensarship_like/XML/Metedata.xml")
    args = parser.parse_args()

    df = pd.read_csv(args.metadata_csv)
    success_df = df
    if "patch_status" in df.columns:
        success_df = df[df["patch_status"].astype(str).str.lower() == "success"].copy()

    timestamps = pd.Series(dtype="datetime64[ns, UTC]")
    if "timestamp" in df.columns:
        timestamps = pd.to_datetime(df["timestamp"], errors="coerce", utc=True)

    root = ET.Element("Metedata")
    root.set("generated_at_utc", timestamp_now_utc())
    root.set("description", "Dataset summary generated by pipeline, not original Sentinel-1 XML")

    add_text(root, "patch_count", len(success_df))
    add_text(root, "category_count", success_df["category_name"].nunique(dropna=True) if "category_name" in success_df.columns else 0)
    if "stac_item_id" in success_df.columns:
        scene_count = success_df["stac_item_id"].nunique(dropna=True)
    elif "original_scene_id" in success_df.columns:
        scene_count = success_df["original_scene_id"].nunique(dropna=True)
    else:
        scene_count = 0
    add_text(root, "scene_count", scene_count)

    time_range = ET.SubElement(root, "time_range")
    if not timestamps.empty and timestamps.notna().any():
        add_text(time_range, "start", timestamps.min().isoformat())
        add_text(time_range, "end", timestamps.max().isoformat())
    else:
        add_text(time_range, "start", "")
        add_text(time_range, "end", "")

    add_text(root, "source_dataset", "Global Fishing Watch SAR Vessel Detections EEZ Indonesia")
    add_text(root, "source_imagery", "Microsoft Planetary Computer Sentinel-1 RTC STAC collection")
    add_text(
        root,
        "note",
        "Patch dibuat dari GFW SAR detections sebagai metadata lokasi kapal dan Sentinel-1 RTC sebagai sumber raster.",
    )

    categories = ET.SubElement(root, "categories")
    if "category_name" in success_df.columns:
        counts = success_df["category_name"].value_counts(dropna=False)
        for category, count in counts.items():
            item = ET.SubElement(categories, "category")
            item.set("name", text_value(category))
            item.set("count", str(int(count)))

    tree = ET.ElementTree(root)
    ET.indent(tree, space="  ")
    output_xml = Path(args.output_xml)
    ensure_parent(output_xml)
    tree.write(output_xml, encoding="utf-8", xml_declaration=True)
    print(f"Metedata XML: {output_xml}")
    print(f"Jumlah patch sukses: {len(success_df)}")


if __name__ == "__main__":
    main()
